version: "3"
services:
    app:
        image: lapytopy/lapis
        container_name: app
        restart: unless-stopped
        volumes:
            - ./src:/app
            - ./logs:/var/log/openresty/
            - openresty_tmp:/tmp/openresty
        ports:
            - 8080

volumes:
    openresty_tmp: