#!/bin/bash

set -e

buildDepsApk="
curl
libc-dev
unzip
wget
"

OLD_IFS="$IFS"
IFS=','
pm='unknown'
if [ -e /lib/apk/db/installed ]; then
    pm='apk'
fi

if [ "$pm" = 'apk' ]; then
    apk add --no-cache ${buildDepsApk}
fi

for arg in $@; do
  echo [LuaRocks] Installing $arg
  luarocks install "$arg"
done

if [ "$pm" = 'apk' ]; then
    apk del ${buildDepsApk}
fi

IFS="$OLD_IFS"