name: Publish Docker Image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  workflow_dispatch:
  

jobs:
  debian:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@master
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.3.0
        with:
          platforms: linux/amd64,linux/arm64
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ltlapy/lapis
          tags: |
            type=edge
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      
      - name: Build Debian version and publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@2.22
        with:
          name: ltlapy/lapis
          tags: "latest,debian"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: Dockerfile
          platforms: linux/amd64,linux/arm64
          tag_semver: true
